#dubbo
spring.dubbo:
  appname: user-provider
  registry: zookeeper://127.0.0.1:2181
  protocol: dubbo

#spring boot
spring:
  aop:
    proxy-target-class: true

#mysql
mysql:
  driver-class: com.mysql.cj.jdbc.Driver
  write-url: jdbc:mysql://localhost:3306/muy_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
  write-username: root
  write-password: yanglikai
  read-url: jdbc:mysql://localhost:3306/muy_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
  read-username: root
  read-password: yanglikai
  filters: stat
  maxActive: 5
  initialSize: 2
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
#redis
redis:
  ip: 10.0.38.200
  port: 6379
  maxTotal: 20
  maxIdle: 10
  testOnBorrow: true
  password: xceof
  timeout: 5000