spring:
  application:
    name: job-provider
  profiles:
    active: dev
server:
  port: 6062

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou